"""Sync the warehouse and model artifacts with GitHub Release assets (tag `warehouse`) using the gh CLI.

    python -m pipeline.release upload [--dry-run]     # after a nightly run
    python -m pipeline.release download [--dry-run]   # at the start of a nightly run (fresh CI checkout)
    python -m pipeline.release prune [--dry-run]      # delete unreferenced versions older than KEEP_DAYS

Manifest-based and change-only (AUDIT R-2):
- Each logical file (`games__2026.parquet`, `model_artifacts.tar.gz`, `shot_bins.tar.gz`) has a content hash. Only files whose
  hash differs from the published manifest are uploaded, each under a NEW versioned name (`games__2026.<hash12>.parquet`),
  so nothing that the current manifest points to is ever overwritten.
- `manifest.json` (logical name -> asset name, sha256) is uploaded LAST. A run that dies mid-upload leaves the previous
  manifest, and every asset it names, intact.
- Download reads the manifest (falls back to the legacy un-versioned names if there is no manifest yet).
- Prune deletes assets that the manifest does not reference and that are older than KEEP_DAYS.
Tarball hashes are over member contents, not tar bytes (tar timestamps change every run).
The prediction log is NOT here: it lives in git (pipeline/predictions/log.py). Play-by-play and raw shots are never published.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import tarfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

from pipeline.warehouse.paths import ROOT, WH

TAG = "warehouse"
TABLES = ["games", "team_games", "player_games", "teams", "team_seasons", "rosters", "player_seasons", "player_impacts", "pbp_scores"]
ART = ROOT / "data" / "backtest"
SHOTS = ROOT / "web" / "public" / "data" / "shots"
STAGE = ROOT / "data" / "stage"
DL = ROOT / "data" / "dl"
MANIFEST = "manifest.json"
KEEP_DAYS = 7  # DEFINITION: unreferenced asset versions are kept this long (rollback window), then pruned


def sh(cmd: list[str], dry: bool, capture: bool = False):
    print(("DRY " if dry else "RUN ") + " ".join(cmd), flush=True)
    if not dry:
        return subprocess.run(cmd, check=True, capture_output=capture, text=capture)


def _sha_file(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _sha_dir(d: Path) -> str:
    h = hashlib.sha256()
    for p in sorted(x for x in d.rglob("*") if x.is_file()):
        h.update(p.relative_to(d).as_posix().encode() + b"\0" + _sha_file(p).encode())
    return h.hexdigest()


def local_files() -> dict[str, dict]:
    """Logical name -> {sha256, kind, src} for everything that should be published."""
    out = {}
    for t in TABLES:
        for p in sorted((WH / t).glob("*.parquet")) if (WH / t).exists() else []:
            out[f"{t}__{p.stem}.parquet"] = {"sha256": _sha_file(p), "kind": "file", "src": str(p)}
    if ART.exists():
        out["model_artifacts.tar.gz"] = {"sha256": _sha_dir(ART), "kind": "tar", "src": str(ART), "arcname": "backtest"}
    if any(SHOTS.glob("*/league.json")):
        out["shot_bins.tar.gz"] = {"sha256": _sha_dir(SHOTS), "kind": "tar", "src": str(SHOTS), "arcname": "shots"}
    return out


def versioned(name: str, sha: str) -> str:
    stem, ext = (name[:-7], ".tar.gz") if name.endswith(".tar.gz") else (name.rsplit(".", 1)[0], "." + name.rsplit(".", 1)[1])
    return f"{stem}.{sha[:12]}{ext}"


def remote_manifest() -> dict | None:
    r = subprocess.run(["gh", "release", "download", TAG, "-p", MANIFEST, "-O", "-"], capture_output=True, text=True)
    return json.loads(r.stdout) if r.returncode == 0 and r.stdout.strip() else None


def plan(local: dict, remote: dict | None) -> list[str]:
    """Logical names whose content differs from the published manifest."""
    have = (remote or {}).get("files", {})
    return [k for k, v in local.items() if have.get(k, {}).get("sha256") != v["sha256"]]


def _stage(name: str, info: dict) -> Path:
    STAGE.mkdir(parents=True, exist_ok=True)
    dst = STAGE / versioned(name, info["sha256"])
    if info["kind"] == "file":
        shutil.copyfile(info["src"], dst)
    else:
        with tarfile.open(dst, "w:gz") as tf:
            tf.add(info["src"], arcname=info["arcname"])
    return dst


def upload(dry=False, remote: dict | None = None, uploader=None) -> dict:
    """Upload changed files, then the manifest. `remote`/`uploader` are injectable for tests and the failure drill."""
    if remote is None and not dry:
        if subprocess.run(["gh", "release", "view", TAG], capture_output=True).returncode != 0:
            sh(["gh", "release", "create", TAG, "--title", "Warehouse", "--notes", "Warehouse tables (parquet) and model artifacts. Generated by the pipeline."], dry)
        remote = remote_manifest()
    elif remote is None:
        remote = remote_manifest()
    local = local_files()
    changed = plan(local, remote)
    up = uploader or (lambda path: sh(["gh", "release", "upload", TAG, str(path)], dry))
    files = dict((remote or {}).get("files", {}))
    for k in changed:
        path = STAGE / versioned(k, local[k]["sha256"]) if dry else _stage(k, local[k])
        for attempt in range(3):  # one asset per call: batched uploads failed intermittently
            try:
                up(path)
                break
            except subprocess.CalledProcessError:
                if attempt == 2:
                    raise
        files[k] = {"asset": versioned(k, local[k]["sha256"]), "sha256": local[k]["sha256"]}
    for k in list(files):  # tables that no longer exist locally drop out of the manifest
        if k not in local:
            files.pop(k)
    man = {"updated": datetime.now(timezone.utc).isoformat(), "files": files}
    STAGE.mkdir(parents=True, exist_ok=True)
    mp = STAGE / MANIFEST
    mp.write_text(json.dumps(man, indent=1))
    if uploader is not None:
        uploader(mp)
    else:
        sh(["gh", "release", "upload", TAG, "--clobber", str(mp)], dry)  # the only asset ever overwritten, and it goes last
    print(f"uploaded {len(changed)} changed file(s) of {len(local)} + manifest", flush=True)
    return {"changed": changed, "manifest": man}


def _place(name: str, path: Path):
    if name.endswith(".tar.gz"):
        with tarfile.open(path) as tf:
            tf.extractall(ART.parent if name.startswith("model_artifacts") else SHOTS.parent)
        return
    t, s = name[:-8].split("__")
    dst = WH / t / f"{s}.parquet"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(path, dst)


def download(dry=False):
    DL.mkdir(parents=True, exist_ok=True)
    man = None if dry else remote_manifest()
    if man is None:  # legacy layout (before the manifest existed)
        sh(["gh", "release", "download", TAG, "--dir", str(DL), "--clobber"], dry)
        if dry:
            return
        for p in DL.glob("*__*.parquet"):
            if re.fullmatch(r"[a-z_]+__\d{4}\.parquet", p.name):
                _place(p.name, p)
        for n in ("model_artifacts.tar.gz", "shot_bins.tar.gz"):
            if (DL / n).exists():
                _place(n, DL / n)
        return
    names = [v["asset"] for v in man["files"].values()]
    for i in range(0, len(names), 50):  # several patterns per call keeps it to a few requests
        sh(["gh", "release", "download", TAG, "--dir", str(DL), "--clobber"] + [x for n in names[i:i + 50] for x in ("-p", n)], dry)
    for name, v in man["files"].items():
        dst = DL / v["asset"]
        got = _sha_file(dst) if v["asset"].endswith(".parquet") else None
        if got is not None and got != v["sha256"]:
            raise RuntimeError(f"{v['asset']}: checksum mismatch")
        _place(name, dst)
    print(f"downloaded {len(man['files'])} files from manifest {man['updated']}", flush=True)


def prune(dry=False, now: datetime | None = None):
    man = remote_manifest()
    if man is None:
        print("no manifest: nothing pruned")
        return []
    keep = {v["asset"] for v in man["files"].values()} | {MANIFEST}
    r = sh(["gh", "release", "view", TAG, "--json", "assets"], False, capture=True)
    assets = json.loads(r.stdout)["assets"]
    cutoff = (now or datetime.now(timezone.utc)) - timedelta(days=KEEP_DAYS)
    old = [a["name"] for a in assets if a["name"] not in keep and datetime.fromisoformat(a["createdAt"].replace("Z", "+00:00")) < cutoff]
    for n in old:
        sh(["gh", "release", "delete-asset", TAG, n, "--yes"], dry)
    print(f"pruned {len(old)} unreferenced asset(s) older than {KEEP_DAYS} days", flush=True)
    return old


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=["upload", "download", "prune"])
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    {"upload": upload, "download": download, "prune": prune}[a.action](a.dry_run)
