"""Sync the warehouse and model artifacts with GitHub Release assets (tag `warehouse`) using the gh CLI.

    python -m pipeline.release upload [--dry-run]     # after a nightly run
    python -m pipeline.release download [--dry-run]   # at the start of a nightly run (fresh CI checkout)

Asset naming: <table>__<season>.parquet, model_artifacts.tar.gz (data/backtest), prediction_log.parquet,
shot_bins.tar.gz (the binned shot-chart shards from pipeline.export.shots, not raw shots).
DECISION (DECISIONS.md): the nightly downloads ALL seasons of the (small) tables because Elo, consensus and the site exports use
full history; play-by-play and raw shots are never published.
"""
from __future__ import annotations

import argparse
import subprocess
import tarfile

from pipeline.warehouse.paths import ROOT, WH

TAG = "warehouse"
TABLES = ["games", "team_games", "player_games", "teams", "team_seasons", "rosters", "player_seasons", "player_impacts"]
ART = ROOT / "data" / "backtest"
LOG = ROOT / "data" / "predictions" / "log.parquet"
SHOTS = ROOT / "web" / "public" / "data" / "shots"


def sh(cmd: list[str], dry: bool):
    print(("DRY " if dry else "RUN ") + " ".join(cmd))
    if not dry:
        subprocess.run(cmd, check=True)


def _stage(src, name, dry):
    """gh names the asset after the file (a '#label' is only a display label), so copy to a correctly named file."""
    import shutil
    dst = ROOT / "data" / "stage" / name
    if not dry:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dst)
    return str(dst)


def upload(dry=False):
    if not dry:
        r = subprocess.run(["gh", "release", "view", TAG], capture_output=True)
        if r.returncode != 0:
            sh(["gh", "release", "create", TAG, "--title", "Warehouse", "--notes",
                "Warehouse tables (parquet), model artifacts and prediction log. Generated by the pipeline."], dry)
    files = []
    for t in TABLES:
        d = WH / t
        for p in sorted(d.glob("*.parquet")) if d.exists() else []:
            files.append(_stage(p, f"{t}__{p.stem}.parquet", dry))
    tgz = ROOT / "data" / "model_artifacts.tar.gz"
    if ART.exists():
        if not dry:
            with tarfile.open(tgz, "w:gz") as tf:
                tf.add(ART, arcname="backtest")
        files.append(str(tgz))
    if LOG.exists():
        files.append(_stage(LOG, "prediction_log.parquet", dry))
    if any(SHOTS.glob("*/league.json")):
        stgz = ROOT / "data" / "shot_bins.tar.gz"
        if not dry:
            with tarfile.open(stgz, "w:gz") as tf:
                tf.add(SHOTS, arcname="shots")
        files.append(str(stgz))
    for f in files:  # one asset per call: batched uploads failed intermittently
        for attempt in range(3):
            try:
                sh(["gh", "release", "upload", TAG, "--clobber", f], dry)
                break
            except subprocess.CalledProcessError:
                if attempt == 2:
                    raise


def download(dry=False):
    out = ROOT / "data" / "dl"
    sh(["gh", "release", "download", TAG, "--dir", str(out), "--clobber"], dry)
    if dry:
        return
    for p in out.glob("*__*.parquet"):
        t, s = p.name[:-8].split("__")
        dst = WH / t / f"{s}.parquet"
        dst.parent.mkdir(parents=True, exist_ok=True)
        p.replace(dst)
    tgz = out / "model_artifacts.tar.gz"
    if tgz.exists():
        with tarfile.open(tgz) as tf:
            tf.extractall(ROOT / "data")
    stgz = out / "shot_bins.tar.gz"
    if stgz.exists():
        with tarfile.open(stgz) as tf:
            tf.extractall(SHOTS.parent)
    lg = out / "prediction_log.parquet"
    if lg.exists():
        LOG.parent.mkdir(parents=True, exist_ok=True)
        lg.replace(LOG)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=["upload", "download"])
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    (upload if a.action == "upload" else download)(a.dry_run)
